# 📱 Mobile Price Range Classification using PyTorch

## 📦 Step 1: Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from torch.utils.data import DataLoader, TensorDataset

## 📂 Step 2: Load the Dataset

In [ ]:
df = pd.read_csv('mobiles.csv')
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

## 🧼 Step 3: Prepare the Data

In [ ]:
X = df.drop('price_range', axis=1).values
y = df['price_range'].values

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

# Create DataLoader
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

## 🧠 Step 4: Build the Neural Network Model

In [ ]:
class PriceClassifier(nn.Module):
    def __init__(self):
        super(PriceClassifier, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(X_train.shape[1], 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 4)  # 4 output classes
        )

    def forward(self, x):
        return self.model(x)

model = PriceClassifier()

## ⚙️ Step 5: Define Loss Function and Optimizer

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

## 🏋️ Step 6: Train the Model

In [ ]:
epochs = 20
for epoch in range(epochs):
    model.train()https://drive.google.com/file/d/1DwIZBq8eA9jozr_fIG9n2f-fim63cR9z/view?usp=sharing
    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

Epoch 1/20, Loss: 1.1073
Epoch 2/20, Loss: 0.6779
Epoch 3/20, Loss: 0.5466
Epoch 4/20, Loss: 0.3691
Epoch 5/20, Loss: 0.3506
Epoch 6/20, Loss: 0.2532
Epoch 7/20, Loss: 0.4007
Epoch 8/20, Loss: 0.4934
Epoch 9/20, Loss: 0.2076
Epoch 10/20, Loss: 0.2532
Epoch 11/20, Loss: 0.1575
Epoch 12/20, Loss: 0.2245
Epoch 13/20, Loss: 0.1992
Epoch 14/20, Loss: 0.3158
Epoch 15/20, Loss: 0.1355
Epoch 16/20, Loss: 0.1557
Epoch 17/20, Loss: 0.1307
Epoch 18/20, Loss: 0.1474
Epoch 19/20, Loss: 0.0726
Epoch 20/20, Loss: 0.2301


## 📊 Step 7: Evaluate the Model

In [ ]:
model.eval()
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred_labels = torch.argmax(y_pred, axis=1)

print("Classification Report:")
print(classification_report(y_test_tensor, y_pred_labels))

print("Confusion Matrix:")
print(confusion_matrix(y_test_tensor, y_pred_labels))

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.94      0.94       105
           1       0.85      0.91      0.88        91
           2       0.96      0.84      0.90        92
           3       0.95      0.98      0.96       112

    accuracy                           0.92       400
   macro avg       0.92      0.92      0.92       400
weighted avg       0.92      0.92      0.92       400

Confusion Matrix:
[[ 99   6   0   0]
 [  7  83   1   0]
 [  0   9  77   6]
 [  0   0   2 110]]
